const Constants = {
  ALL_ITEMS: "ALL_ITEMS",
  INCREASE_IN_LIST: "INCREASE_IN_LIST",
  DECREASE_IN_LIST: "DECREASE_IN_LIST",
  ADD_TO_CART: "ADD_TO_CART",
  DEL_FROM_CART: "DEL_FROM_CART",
  INCREASE_IN_CART: "INCREASE_IN_CART",
  DECREASE_IN_CART: "DECREASE_IN_CART",
};

export default Constants;
